[build]
builder = "nixpacks"
buildCommand = "dotnet publish NotificationService.API/NotificationService.API.csproj --no-restore -c Release -o out"

[start]
cmd = "dotnet out/NotificationService.API.dll"

